### ISSUE TITLE
Decouple business logic from proposal logic

### ISSUE THREAD

**Issue by ariel-dao** [daostack/common-backend#1504]
Business logic (i.e assign circle, create circle, etc.) is coupled with the proposal execution, need to to decouple the logic so it'll be used as action and also chainable actions that depend on one another

### Affected proposals/actions
- `Assign circle` (proposal)
- `Remove circle` (proposal)
- `Create subcommon` (action)
- `Delete common` (proposal)
- `Member admittance` (proposal)

### Task list
- [ ] Create util functions for `check required args for action execution`
- [ ] Create util functions for `check validity of action args`
- [ ] Add action required logic limitation (if needed) to `governance.actions[ACTION]` object
- [ ] Create execute action functions for business logic that is currently in the proposals
- [ ] Rename proposal related logic to fit the functionality (i.e `createCircle` -> `createCreateCircleProposal`)
- [ ] Review `proposal` related events to make sure actions don't miss out on async logic

This task has no affect on frontend other than opening the option to execute certain business logic through actions if it's defined in the governance.

**Comment by ariel-dao** [comment]
Filled by https://github.com/daostack/common-backend/commit/62dceec51d3d7b2eaab2dd3f31907db1b2b1e2ba
But I won't close this one yet, because it's not fully implemented for all proposals and the structure is still a little messy for my taste
