### ISSUE TITLE
Better Discussions Batch #2

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#227]
👩🏼‍💻 Main dev @watchtower314 
📝 [Notion description](https://www.notion.so/daostack/Better-discussion-Batch-2-7631fb3fb33b4f30a26613e81c823ced)

📋 Related tasks:
- [x] #245 Discussions - Design fixes 
- [x] #246 New post - Redesign
- [x] #247 Discussions - Post content arrow logic

❌ Related bugs:

**Comment by yanivi71** [comment]
Verified on production
