### ISSUE TITLE
MOBILE: Migration to graphql/Postgres from Firebase

### ISSUE THREAD

**Issue by MeyerPV** [daostack/common-backend#481]
- [x] [User objects Postgres migration](https://github.com/daostack/common-monorepo/issues/503) 
- [x] [Common objects Postgres migration](https://github.com/daostack/common-monorepo/issues/505) 
- [x] [Proposal objects Postgres migration](https://github.com/daostack/common-monorepo/issues/506) 
- [x] [Discussion objects Postgres migration](https://github.com/daostack/common-monorepo/issues/507) 
- [x] [Message objects Postgres migration](https://github.com/daostack/common-monorepo/issues/508) 
- [ ] [Notification objects Postgres migration](https://github.com/daostack/common-monorepo/issues/509)
