### ISSUE TITLE
Change currency tickets

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#970]
- [x] https://github.com/daostack/common-monorepo/issues/881 - My Profile screen
- [x] https://github.com/daostack/common-monorepo/issues/893 -> Create Common flow
- [x] https://github.com/daostack/common-monorepo/issues/883 -> Billing (we might not have this screen yet though)
- [x] https://github.com/daostack/common-monorepo/issues/914 -> Create funding proposal
- [x] Common profile screen -> https://github.com/daostack/common-monorepo/issues/914, 
- [x] https://github.com/daostack/common-monorepo/issues/915 -> request to join
- [x] https://github.com/daostack/common-monorepo/issues/890 -> notifications
- [x] https://github.com/daostack/common-monorepo/issues/906 -> common agenda
- [x] https://github.com/daostack/common-monorepo/issues/920 -> proposal screen
- [x] https://github.com/daostack/common-monorepo/issues/926 -> emails

**Comment by yanivi71** [comment]
Tested on staging and found OK
